# Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    groups:
      critical-dependencies:
        patterns:
          - '@content-island/vscode-api-client'
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@content-island/vscode-api-client'
        update-types:
          - 'minor'
          - 'patch'
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'
