name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    environment:
      name: Marketplace Portal
      url: https://marketplace.visualstudio.com/manage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:package

      - name: Publish Release
        uses: changesets/action@v1
        with:
          publish: npm run publish:package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.CONTENT_ISLAND_VSCE_TOKEN }}
